[package]
name = "locus-civitai"
version = "0.1.0"
edition = "2024"

[dependencies]
locus-task.workspace = true
locus-core.workspace = true
locus-file.workspace = true
locus-media.workspace = true
locus-store.workspace = true
diesel.workspace = true
diesel-async.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
tokio.workspace = true
tempfile.workspace = true
blake3 = "1"
reqwest = { version = "=0.13.4", features = ["json"] }
provider-civitai = { git = "https://github.com/CherryGS/provider-rs.git", rev = "5c5da6dd5d5beac04d26de4e959fa4b3d80d23a8" }

[dev-dependencies]
locus-migration.workspace = true
image.workspace = true
tokio-rustls = "0.26"
