[workspace]
resolver = "3"
members = ["apps/locus", "crates/locus-task", "crates/locus-store", "crates/locus-core", "crates/locus-file", "crates/locus-media", "crates/provider/locus-twitter"]

[workspace.dependencies]
anyhow = "1"
directories = "6"
diesel = { version = "=2.3.13", default-features = false, features = ["sqlite"] }
diesel-async = { version = "=0.9.2", default-features = false, features = ["sqlite"] }
libsqlite3-sys = { version = "0.37", features = ["bundled"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "process", "io-util"] }
thiserror = "2"
uuid = { version = "1", features = ["v7"] }
tempfile = "3"
locus-store = { path = "crates/locus-store" }
locus-task = { path = "crates/locus-task" }
locus-core = { path = "crates/locus-core" }
locus-file = { path = "crates/locus-file" }
locus-media = { path = "crates/locus-media" }
locus-twitter = { path = "crates/provider/locus-twitter" }
image = { version = "=0.25.10", default-features = false, features = ["png", "jpeg", "webp", "gif"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "=2.5.8"

[profile.dev]
opt-level = 1
debug = "line-tables-only"
debug-assertions = true
overflow-checks = true
incremental = true
lto = false
codegen-units = 256
panic = "unwind"

[profile.dev.package."*"]
opt-level = 3
debug = false

[profile.release]
opt-level = 3
debug = "line-tables-only"
debug-assertions = false
overflow-checks = false
incremental = false
lto = "thin"
codegen-units = 8
panic = "unwind"
strip = "none"

[profile.dist]
inherits = "release"
opt-level = 3
debug = "line-tables-only"
lto = "thin"
codegen-units = 1
incremental = false
panic = "unwind"
strip = "none"
