[package]
name = "locus"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
gpui-kit = "=0.6.4"

[dev-dependencies]
locus-task.workspace = true
image.workspace = true
locus-core.workspace = true
locus-store.workspace = true
tokio.workspace = true
locus-file.workspace = true
locus-media.workspace = true
locus-twitter.workspace = true
directories.workspace = true
tempfile.workspace = true

[[example]]
name = "file-backend"
test = true

[[example]]
name = "media-backend"
test = true

[[example]]
name = "twitter-backend"
test = true

[[example]]
name = "task-backend"
test = true
