[package]
name = "locus-twitter"
version = "0.1.0"
edition = "2024"

[dependencies]
locus-task.workspace = true
locus-core.workspace = true
locus-file.workspace = true
locus-store.workspace = true
diesel.workspace = true
diesel-async.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
url.workspace = true

[dev-dependencies]
locus-migration.workspace = true
tokio.workspace = true
tempfile.workspace = true
locus-media.workspace = true
image.workspace = true
