[package]
name = "locus-media"
version = "0.1.0"
edition = "2024"

[dependencies]
locus-settings.workspace = true
schemars.workspace = true
locus-task.workspace = true
locus-core.workspace = true
locus-file.workspace = true
locus-store.workspace = true
diesel.workspace = true
diesel-async.workspace = true
tokio.workspace = true
thiserror.workspace = true
uuid.workspace = true
image.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
